(define (problem teste001)
    (:domain hotel_domain)
    (:objects
        Bruno Otaviano Casimiro Igor DavyJones Iasmine Chris Vanessa Rose - pessoa
        quarto1 quarto2 quarto3 quarto4 quarto5 quarto6 quarto7 quarto8 quarto9 quarto10 - quarto
    )
    (:init
        (homem Bruno)
        (homem Otaviano)
        (homem Casimiro)
        (homem Igor)
        (homem DavyJones)
        (mulher Iasmine)
        (mulher Chris)
        (mulher Vanessa)
        (mulher Rose)
        (casal Bruno Rose)
        (casal Otaviano Vanessa)
        (quartoCasal quarto1)
        (= (custo quarto1) 100)
        (quartoCasal quarto2)
        (= (custo quarto2) 150)
        (quartoCasal quarto3)
        (= (custo quarto3) 1000)
        (quartoDuplo quarto4)
        (= (custo quarto4) 150)
        (quartoDuplo quarto5)
        (= (custo quarto5) 200)
        (quartoTriplo quarto6)
        (= (custo quarto6) 250)
        (quartoTriplo quarto7)
        (= (custo quarto7) 600)
        (quartoTriplo quarto8)
        (= (custo quarto8) 250)
        (quartoQuadruplo quarto9)
        (= (custo quarto9) 360)
        (quartoQuadruplo quarto10)
        (= (custo quarto10) 990)
    )
    (:goal
        (and
            (alojada Bruno)
            (alojada Otaviano)
            (alojada Casimiro)
            (alojada Igor)
            (alojada DavyJones)
            (alojada Iasmine)
            (alojada Chris)
            (alojada Vanessa)
            (alojada Rose)
        )
    )
    (:metric minimize
        (total-cost)
    )
)