(define (problem teste001)
  (:domain hotel_domain)
  (:objects homem1 homem2 homem3 homem4 - homem
            mulher1 mulher2 mulher3 mulher4 - mulher
            quarto1 quarto2 quarto3 quarto4 quarto5 quarto6 - quarto
            orc - orcamento)

  (:init (casal homem1 mulher1)
        (casal homem2 mulher2)
        (casal homem3 mulher3)
        (casal homem4 mulher4)
        (= (vagas quarto1) 2)
        (= (vagas quarto2) 2)
        (= (vagas quarto3) 2)
        (= (vagas quarto4) 2)
        (= (vagas quarto5) 2)
        (= (vagas quarto6) 2)
        (= (max-vagas quarto1) 2)
        (= (max-vagas quarto2) 2)
        (= (max-vagas quarto3) 2)
        (= (max-vagas quarto4) 2)
        (= (max-vagas quarto5) 2)
        (= (max-vagas quarto6) 2)
        (= (custo quarto1) 1230)
        (= (custo quarto2) 500)
        (= (custo quarto3) 400)
        (= (custo quarto4) 300)
        (= (custo quarto5) 200)
        (= (custo quarto6) 100)
        (= (total orc) 0)      
  )
  (:goal (and
    (no-quarto homem1)
    (no-quarto homem2)
    (no-quarto homem3)
    (no-quarto homem4)
    (no-quarto mulher1)
    (no-quarto mulher2)
    (no-quarto mulher3)
    (no-quarto mulher4)
  ))

  (:metric minimize (total orc) )
)
